-- YSSCHOOL shared content schema
-- Apply this migration to the Supabase project used by ysschool.vercel.app.

create table if not exists public.training_materials (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  description text not null check (char_length(description) between 1 and 1000),
  category text not null check (category in ('에듀테크', 'AI활용', '독서인문', '기타')),
  date date not null default current_date,
  link text,
  file_url text,
  file_type text,
  thumbnail text,
  created_at timestamptz not null default now()
);

create table if not exists public.schedule_events (
  id bigint generated by default as identity primary key,
  date date not null,
  title text not null check (char_length(title) between 1 and 120),
  location text not null check (char_length(location) between 1 and 120),
  time text not null check (char_length(time) between 1 and 60),
  target text not null check (char_length(target) between 1 and 120),
  type text not null check (type in ('training', 'lecture', 'performance', 'consulting')),
  created_at timestamptz not null default now()
);

create table if not exists public.guestbook_entries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 20),
  affiliation text,
  message text not null check (char_length(message) between 1 and 300),
  client_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists training_materials_date_idx
  on public.training_materials (date desc, created_at desc);

create index if not exists schedule_events_date_idx
  on public.schedule_events (date asc, time asc);

create index if not exists guestbook_entries_created_idx
  on public.guestbook_entries (created_at desc);

create index if not exists guestbook_entries_rate_idx
  on public.guestbook_entries (client_hash, created_at desc);

alter table public.training_materials enable row level security;
alter table public.schedule_events enable row level security;
alter table public.guestbook_entries enable row level security;

-- No anon/authenticated policies are intentionally created.
-- The Next.js server routes use the Supabase service role and are the only write/read gateway.

insert into storage.buckets (id, name, public)
values ('training-files', 'training-files', true)
on conflict (id) do update set public = excluded.public;
